SmartHouseMVC/Models/Applience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace SmartHouseMVC.Models
{
    public abstract class Applience: ISwitchable
    {
        private bool state;
        private string name;
        public string Name
        {
            protected set
            {
                name = value;
            }
             get
        {
            return name;
        }
        }
        public bool State
        {
            set
            {
                state = value;
            }
            get
            {
                return state;
            }
        }
        public  void OnOff()
        {
            if (State)
            {
                State = false;
            }
            else
            {
                State = true;
            }
        }
        public virtual string ShowStatus()
        {
            string status = " ";
            if (State)
                status = name+" is on " ;
            else
                status = name+" is off";
            return status;
        }
    }
}

SmartHouseMVC/Models/ImplementedInterfaces/Applience.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SmartHouseMVC.Models.Interfaces;

namespace SmartHouseMVC.Models.ImplementedInterfaces
{
    public abstract class Applience: ISwitchable
    {

        public int Id { get; set; }
        
        public string Name
        {
           get;set;
        }

        public bool State
        {
            get;
            set;
        }
        public  void OnOff()
        {
            if (State)
            {
                State = false;
            }
            else
            {
                State = true;
            }
        }
        public override string ToString()

        {
            string status = " ";
            if (State)
                status = Name+" is on " ;
            else
                status = Name+" is off";
            return status;
        }
    }
}

SmartHouseMVC/Models/ImplementedInterfaces/TV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SmartHouseMVC.Models.Interfaces;
namespace SmartHouseMVC.Models.ImplementedInterfaces
{
    public class TV : Applience, IChannel, IChangeable
    {
        public IList<string> channels;
        public string currentChannel;
        public TV()
        {

        }
        public TV(string name, int unit, int max, IList<string> listOfChannels, int positionOfCurrentChan)
        {
            Name = name;
            channels = listOfChannels;
            currentChannel = channels.ElementAt(positionOfCurrentChan);
            Unit = unit;
            Max = max;
        }
        public int Max
        {
            get;
            set;
        }
        public int Unit
        {
            get;
            set;
        }

        public IList<string> ShowChannels()
        {
            if (this.State)
                return channels;
            else
                return null;
        }
        public void AddChannel(string channel)
        {

            channels.Add(channel);
        }
        public void Up()
        {
            if (State)
            {
                if (Unit == Max)
                    Unit = 0;
                else
                    Unit++;
            }
        }
        public void Down()
        {
            if (State)
            {
                if (Unit == 0)
                    Unit = Max;
                else
                    Unit--;
            }
        }
        public override string ToString()

        {
            string status = base.ToString();

            if (State)
                status += " current volume " + Unit + " current channel " + currentChannel;

            return status;
        }
        public void NextChannel()
        {
            if (State)
            {
                int index = channels.IndexOf(currentChannel);
                if (index == (channels.Count - 1))
                    currentChannel = channels[0];
                else
                    currentChannel = channels[++index];
            }
        }
        public void PrevChannel()
        {
            if (State)
            {
                int index = channels.IndexOf(currentChannel);
                if (index == 0)
                    currentChannel = channels[channels.Count - 1];
                else
                    currentChannel = channels[--index];
            }
        }
        public void DeleteCurrentCh()
        {
            if (State)
            {
                bool flag = false;
                int pos = channels.IndexOf(currentChannel);


                if ((pos + 1) == channels.Count)
                {
                    currentChannel = channels[0];
                    flag = true;
                }


                if ((pos + 1) == channels.Count && channels.Count == 1)
                {

                    currentChannel = "none";
                    flag = true;
                }

                if (!flag)
                {
                    currentChannel = channels[pos + 1];
                }
                channels.RemoveAt(pos);
            }
        }
    }
}

SmartHouseMVC/Models/TV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SmartHouseMVC.Models
{
    public class TV : Applience, IChannel, IChangeable
    {
        public IList<string> channels;
        public string currentChannel;
        int max = 20;
        public TV(string name, int unit, int max, IList<string> listOfChannels, int positionOfCurrentChan)
        {
            Name = name;
            channels = listOfChannels;
            currentChannel = channels.ElementAt(positionOfCurrentChan);
            Unit = unit;
            this.max = max;
        }
        public int Unit
        {
            get;
            private set;
        }

        public IList<string> ShowChannels()
        {
            if (this.State)
                return channels;
            else
                return null;
        }
        public void AddChannel(string channel)
        {

            channels.Add(channel);
        }
        public void Up()
        {
            if (State)
            {
                if (Unit == max)
                    Unit = 0;
                else
                    Unit++;
            }
        }
        public void Down()
        {
            if (State)
            {
                if (Unit == 0)
                    Unit = max;
                else
                    Unit--;
            }
        }
        public override string ShowStatus()
        {
            string status = base.ShowStatus();

            if (State)
                status += " current volume " + Unit + " current channel " + currentChannel;

            return status;
        }
        public void NextChannel()
        {
            if (State)
            {
                int index = channels.IndexOf(currentChannel);
                if (index == (channels.Count - 1))
                    currentChannel = channels[0];
                else
                    currentChannel = channels[++index];
            }
        }
        public void PrevChannel()
        {
            if (State)
            {
                int index = channels.IndexOf(currentChannel);
                if (index == 0)
                    currentChannel = channels[channels.Count - 1];
                else
                    currentChannel = channels[--index];
            }
        }
        public void DeleteCurrentCh()
        {
            if (State)
            {
                bool flag = false;
                int pos = channels.IndexOf(currentChannel);


                if ((pos + 1) == channels.Count)
                {
                    currentChannel = channels[0];
                    flag = true;
                }


                if ((pos + 1) == channels.Count && channels.Count == 1)
                {

                    currentChannel = "none";
                    flag = true;
                }

                if (!flag)
                {
                    currentChannel = channels[pos + 1];
                }
                channels.RemoveAt(pos);
            }
        }
    }
}

SmartHouseMVC/Controllers/ApplienceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SmartHouseMVC.Models.Interfaces;
using SmartHouseMVC.Models.ImplementedInterfaces;
using SmartHouseMVC.Models.Factory;
using SmartHouseMVC.Models.MyDbContext;


namespace SmartHouseMVC.Controllers
{
    public class ApplienceController : Controller
    {
        // GET: Applience
        ApplienceContext db = new ApplienceContext();
        public ActionResult Index()
        {
            IList<Applience> list=new List<Applience>();
           
            foreach(Applience item in db.Lamps.ToList())
            {
                list.Add(item);
            }
            foreach(Applience item in db.Conditioneres.ToList())
            {
                list.Add(item);
            }
            foreach(Applience item in db.Microwaves.ToList())
            {
                list.Add(item);
            }
           foreach(Applience item in db.TVs.ToList())
           {
               list.Add(item);
           }

            SelectListItem[] appList = new SelectListItem[4];
            appList[0] = new SelectListItem { Text = "Lamp", Value = "lamp", Selected = true };
            appList[1] = new SelectListItem { Text = "Conditioner", Value = "conditioner" };
            appList[2] = new SelectListItem { Text = "Microwave", Value = "microwave" };
            appList[3] = new SelectListItem { Text = "TV", Value = "tv" };
            ViewBag.AppList = appList;

            return View(list);
        }
        public ActionResult Add(string app)
        {
            Applience newApp;
            ApplienceFactory appCreate;

            switch (app)
            {
                   
                default:
                    appCreate = new LampCreator();
                    newApp = appCreate.CreateApplience();
                    db.Lamps.Add((Lamp)newApp);
                    break;
                case "conditioner":
                    appCreate = new ConditionerCreator();
                    newApp = appCreate.CreateApplience();
                    db.Conditioneres.Add((Conditioner)newApp);
                    break;
                case "microwave":
                    appCreate = new MicrowaveCreator();
                    newApp = appCreate.CreateApplience();
                    db.Microwaves.Add((Microwave)newApp);
                    break;
                case "tv":
                    appCreate = new TVCreator();
                    newApp = appCreate.CreateApplience();
                    db.TVs.Add((TV)newApp);
                    break;
            }
              db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Switch(int id, string name)
        {
            ISwitchable app;
            switch(name)
            {
                
                case "Conditioner":
                    {
                        app = db.Conditioneres.Find(id);
                        break;
                    }
                case "Microwave":
                    {
                        app = db.Microwaves.Find(id);
                        break;
                    }
                case "TV":
                    {
                        app = db.TVs.Find(id);
                        break;
                    }
                default:
                    {
                        app = db.Lamps.Find(id);
                        break;
                    }
            }
         
            app.OnOff();
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Change(int id,string name, string action)
        {
            IChangeable app;
            switch (name)
            {
               
                case "Microwave":
                    {
                        app = db.Microwaves.Find(id);
                        break;
                    }
                case "TV":
                    {
                        app = db.TVs.Find(id);
                        break;
                    }
                default:
                    {
                        app = db.Lamps.Find(id);
                        break;
                    }
            }

            switch (action)
            {
                case "Down":
                    app.Down();
                    break;
                case "Up":
                    app.Up();
                    break;
            }
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Temperature(int id,string name, string action, string temperatureTB)
        {
            ITemperatureable app;
            if(name=="Conditioner")
            {
                app = db.Conditioneres.Find(id);
            }
            else
            {
                app = null;
            }

            if (action == "Temperature")
            {
                app.Temperature = Convert.ToInt32(temperatureTB);
                app.AirConditioning();
                TempData["conditioner"] = app.Airconditioning;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Cook(int id,string name, string action)
        {
            ICook app;
            if(name=="Microwave")
            {
                app = db.Microwaves.Find(id);
            }
            else
            {
                app = null;
            }
            if (action == "Food")
            {
                app.Food = true;

                app.Cook();
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult ChannelMethod(int id,string name, string action, string channelTV)
        {
            IList<string> list;
            IChannel app;
            if(name=="TV")
            {
                app = db.TVs.Find(id);
            }
            else
            {
                app = null;
            }
            switch (action)
            {

                case "DeleteChannel":
                    app.DeleteCurrentCh();
                    break;
                case "AddChannel":
                    app.AddChannel(channelTV);
                    break;
                case "Prev":
                    app.PrevChannel();
                    break;
                case "Next":
                    app.NextChannel();
                    break;

                case "show":
                    list = app.ShowChannels();
                    TempData["List"] = list;
                    break;

            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id,string name)
        {
            Applience app;
            switch (name)
            {

                case "Conditioner":
                    {
                        app = db.Conditioneres.Find(id);
                        db.Conditioneres.Remove((Conditioner)app);
                        break;
                    }
                case "Microwave":
                    {
                        app = db.Microwaves.Find(id);
                        db.Microwaves.Remove((Microwave)app);
                        break;
                    }
                case "TV":
                    {
                        app = db.TVs.Find(id);
                        db.TVs.Remove((TV)app);
                        break;
                    }
                default:
                    {
                        app = db.Lamps.Find(id);
                        db.Lamps.Remove((Lamp)app);
                        break;
                    }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SmartHouseMVC/Views/Applience/Index.cshtml
@using SmartHouseMVC.Models.Interfaces
@using SmartHouseMVC.Models.ImplementedInterfaces
@model IList<Applience>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Add", "Applience"))
{
    @Html.DropDownList("app", (IEnumerable<SelectListItem>)ViewBag.AppList)
    <input type="submit" value="Добавить" class="btn btn-default">
}
@foreach (Applience item in Model)
{
    <div class="app-div">
        <span class="labelstyle"> @item.Name </span>
        <br />
        @if (item is ISwitchable)
        {
            using (@Html.BeginForm("Switch" + '/' + item.Id+'/'+item.Name, "Applience"))
            {
                switch (item.Name)
                {
                    case "Lamp":
                        {

                            <input type="image" name="action" value="OnOff" class="img-thumbnail"  src="~/Images/15-Light-Bulb-icon1.png" />
                            break;
                        }
                    case "Conditioner":
                        {
                            <input type="image" name="action" value="OnOff" id="conButton" class="img-thumbnail"  src="~/Images/112132-2001.png" />
                            break;
                        }
                    case "Microwave":
                        {
                            <input type="image" name="action" value="OnOff" id="MicroButton" class="img-thumbnail" src="~/Images/microwave-icon-201.png" />
                            break;
                        }
                    case "TV":
                        {
                            <input type="image" name="action" value="OnOff" class="img-thumbnail"  src="~/Images/retro-tv-icon-615261.png" />
                            break;
                        }
                }
                <br />
            }
        }
        @if (item is IChangeable)
        {

            using (@Html.BeginForm("Change"+'/' + item.Id+'/'+item.Name, "Applience"))
            {
               
                <br />
                <button type="submit" name="action" value="Down" class="btn btn-warning">-</button>
                <button type="submit" name="action" value="Up" class="btn btn-success">+</button>
                <br />
            }
        }
        @if (item is ITemperatureable)
        {
            using (@Html.BeginForm("Temperature" + '/' + item.Id+'/'+item.Name, "Applience", FormMethod.Post, new { id = "myForm" }))
            {
                <span id="spanOnOffcon" hidden="hidden">@item.State</span>
                <br />
                <input type="text" name="temperatureTB" id="temperatureTB" />
                <input type="button" id="setButton" value="Set" class="btn btn-primary" />
                <br />
            }
            <span id="spanState">
                @if (TempData["conditioner"] != null)
                {
                    @TempData["conditioner"];
                }

            </span>

        }

        @if (item is ICook)
        {

            using (@Html.BeginForm("Cook"+'/' + item.Id+'/'+item.Name, "Applience", FormMethod.Post, new { id = "myForm2" }))
            {
                
                <span id="spanOnOff" hidden="hidden">@item.State</span>
                <br />
                <br />
                <input type="text" name="microTB" id="microTB" />
                <label> <input type="checkbox" name="action" value="Food" id="checkbox" />Food </label>
                <button type="button"  value="Reheat" id="reheatButton" class="btn btn-info">Reheat</button>
                <br />
               

            }
        }
        @if (item is IChannel)
        {

            using (@Html.BeginForm("ChannelMethod" + '/' + item.Id+'/'+item.Name, "Applience"))
            {

                
                <br />
                <br />
                <button type="submit" name="action" value="show" class="btn btn-primary">Show</button>
                if ((List<string>)TempData["List"] != null)
                {
                    Html.RenderPartial("TV", (List<string>)TempData["List"]);
                }
                <br />
                <input type="text" name="channelTV" />
                <button type="submit" name="action" value="AddChannel" class="btn btn-primary">Add Channel</button>
                <br />
    <button type="submit" name="action" value="DeleteChannel" class="btn btn-warning">Delete current channel</button>
                <br />
                <button type="submit" name="action" value="Prev" class="btn btn-info"><-</button>
                <button type="submit" name="action" value="Next" class="btn btn-primary">-></button>
            }
        }
        <br />
        <div id="results"></div>
        <span class="labelStatus">@item.ToString()</span>
        <br />
        @using(@Html.BeginForm("Delete/"+item.Id+'/'+item.Name,"Applience"))
        { 
        <button type="submit" class="btn btn-danger">Delete</button>
        }

        
    </div>
   
}
<script src="~/Scripts/CountDownFunctions.js"></script>

SmartHouseMVC/Views/Applience/TV.cshtml
@model IList<string>

<select multiple>
    @foreach (string item in Model)
    {
        <option>@item</option>
    }

</select>